HCopy -C config/hcopyWAV wav/loc1-1.wav wav/loc1-1.mfc
HCopy -C config/hcopyWAV wav/loc1-2.wav wav/loc1-2.mfc
HCopy -C config/hcopyWAV wav/loc1-3.wav wav/loc1-3.mfc
HCopy -C config/hcopyWAV wav/loc1-4.wav wav/loc1-4.mfc
HCopy -C config/hcopyWAV wav/loc1-5.wav wav/loc1-5.mfc
HCopy -C config/hcopyWAV wav/loc1-6.wav wav/loc1-6.mfc
HCopy -C config/hcopyWAV wav/loc1-7.wav wav/loc1-7.mfc
HCopy -C config/hcopyWAV wav/loc1-8.wav wav/loc1-8.mfc
HCopy -C config/hcopyWAV wav/loc1-9.wav wav/loc1-9.mfc
HCopy -C config/hcopyWAV wav/loc1-10.wav wav/loc1-10.mfc
HCopy -C config/hcopyWAV wav/loc1-11.wav wav/loc1-11.mfc
HCopy -C config/hcopyWAV wav/loc1-12.wav wav/loc1-12.mfc
HCopy -C config/hcopyWAV wav/loc1-13.wav wav/loc1-13.mfc
HCopy -C config/hcopyWAV wav/loc1-14.wav wav/loc1-14.mfc
HCopy -C config/hcopyWAV wav/loc1-15.wav wav/loc1-15.mfc
HCopy -C config/hcopyWAV wav/loc1-16.wav wav/loc1-16.mfc
HCopy -C config/hcopyWAV wav/loc1-17.wav wav/loc1-17.mfc
HCopy -C config/hcopyWAV wav/loc1-18.wav wav/loc1-18.mfc
HCopy -C config/hcopyWAV wav/loc2-1.wav wav/loc2-1.mfc
HCopy -C config/hcopyWAV wav/loc2-2.wav wav/loc2-2.mfc
HCopy -C config/hcopyWAV wav/loc2-3.wav wav/loc2-3.mfc
HCopy -C config/hcopyWAV wav/loc2-4.wav wav/loc2-4.mfc
HCopy -C config/hcopyWAV wav/loc2-5.wav wav/loc2-5.mfc
HCopy -C config/hcopyWAV wav/loc2-6.wav wav/loc2-6.mfc
HCopy -C config/hcopyWAV wav/loc2-7.wav wav/loc2-7.mfc
